# Generated by Django 5.1.1 on 2024-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adtitle", models.CharField(max_length=200)),
                ("addescription", models.TextField()),
                ("adimage", models.ImageField(upload_to="ads/images/")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
